version: 1.0.{build}
image: Visual Studio 2017
install:
  - ps: nuget update -self
build_script:
  - ps: nuget pack
deploy:
  - provider: NuGet
    api_key:
      secure: pODLcXDmkbdHzfl9Cu4kAQkwCOh4I4CGkKSJE3NXswFugwpGpbwN/WQ0GPhQbujv
    skip_symbols: true
    artifact: "*.nupkg"
